// Example responses from https://rapidapi.com/letscrape-6bRBa3QguO5/api/jsearch/

export const estimatedSalaryResponse = {
  status: "OK",
  request_id: "7e264821-3ef0-4860-ae0d-ee2ef601ebc4",
  parameters: {
    job_title: "nodejs developer",
    location: "new-york, ny, usa",
    radius: 100,
  },
  data: [
    {
      location: "New York, NY",
      job_title: "NodeJS Developer",
      publisher_name: "Salary.com",
      publisher_link:
        "https://www.salary.com/research/salary/recruiting/nodejs-developer-salary/new-york-ny",
      min_salary: 101323,
      max_salary: 150015,
      median_salary: 123104,
      salary_period: "YEAR",
      salary_currency: "USD",
    },
    {
      location: "New York, NY",
      job_title: "Node JS Developer",
      publisher_name: "ZipRecruiter",
      publisher_link:
        "https://www.ziprecruiter.com/Salaries/Node-JS-Developer-Salary--in-New-York",
      min_salary: 92994,
      max_salary: 158637,
      median_salary: 122925,
      salary_period: "YEAR",
      salary_currency: "USD",
    },
    {
      location: "New York, NY",
      job_title: "node js developer",
      publisher_name: "Talent.com",
      publisher_link:
        "https://www.talent.com/salary?job=node+js+developer&location=new+york",
      min_salary: 82895,
      max_salary: 167450,
      median_salary: 127400,
      salary_period: "YEAR",
      salary_currency: "USD",
    },
  ],
} as const;

export const jobDetailsResponse = {
  status: "OK",
  request_id: "93f618f2-c87d-432b-9ab9-e9b157f8f1f8",
  parameters: {
    job_id: "iXki4pXSSRwAAAAAAAAAAA==",
    extended_publisher_details: false,
  },
  data: [
    {
      employer_name: "TEKsystems",
      employer_logo:
        "https://www.teksystems.com/-/media/teksystems/images/logos/teksystems-logo.svg?iar=0&rev=7059329eede9499a9965f7b1d91cc97f",
      employer_website: "http://www.teksystems.com",
      employer_company_type: "Staffing",
      job_publisher: "TEKsystems Careers",
      job_id: "iXki4pXSSRwAAAAAAAAAAA==",
      job_employment_type: "FULLTIME",
      job_title: "Python Developer (W2)",
      job_apply_link:
        "https://careers.teksystems.com/us/en/job/JP-003793389/Python-Developer-W2",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.9674,
      job_description:
        "Description:\n\nPython Developer in Houston Texas. W2 only. Contract. Hybrid.\n\nSkills:\n\nPython, React, Linux, Unix, API\n\nAdditional Skills & Qualifications:\n\nRequired Skills-\n\n• Strong development experience using Python, REST API Service\n\n• 3+ years of extensive experience working as a full stack React JS developer (familiarity with redux a plus)\n\n• Database development skills, experience with Object-oriented and Relational databases - SQL Server/Oracle/Sybase.\n\n• Experience developing software using Agile methodology.\n\n• Knowledge of JIRA tools and Continuous Integration capabilities.\n\n• Familiarity with web services, web sockets and microservice based architecture is a plus\n\n• Hands on experience in writing unit and UI integration test cases.\n\nExperience Level:\n\nIntermediate Level\n\nAbout TEKsystems:\n\nWe're partners in transformation. We help clients activate ideas and solutions to take advantage of a new world of opportunity. We are a team of 80,000 strong, working with over 6,000 clients, including 80% of the Fortune 500, across North America, Europe and Asia. As an industry leader in Full-Stack Technology Services, Talent Services, and real-world application, we work with progressive leaders to drive change. That's the power of true partnership. TEKsystems is an Allegis Group company.\n\nThe company is an equal opportunity employer and will consider all applications without regards to race, sex, age, color, religion, national origin, veteran status, disability, sexual orientation, gender identity, genetic information or any characteristic protected by law.",
      job_is_remote: false,
      job_posted_at_timestamp: 1684773292,
      job_posted_at_datetime_utc: "2023-05-22T16:34:52.000Z",
      job_city: "Houston",
      job_state: "TX",
      job_country: "US",
      job_latitude: 29.760427,
      job_longitude: -95.369804,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&q=iXki4pXSSRwAAAAAAAAAAA%3D%3D&cs=1&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=iXki4pXSSRwAAAAAAAAAAA%3D%3D&htidocid=iXki4pXSSRwAAAAAAAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: null,
      job_offer_expiration_timestamp: null,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: 36,
        experience_mentioned: true,
        experience_preferred: true,
      },
      job_required_skills: [
        "Python",
        "Redux",
        "ui integration",
        "REST API",
        "UI",
        "Jira",
        "Full Stack",
        "Linux",
        "SQL Server",
        "Agile Methodology",
        "Unix",
        "React",
        "Oracle",
        "Continuous Integration",
        "jira tools",
        "Integration",
        "Database Development",
        "Sybase",
        "Architecture",
        "Web Services",
        "Technology Services",
        "Transformation",
        "Writing",
        "Development",
        "Senior Developer & Software Engineer .Net & Full Stack Developer & Full Stack Software Engineer .Net",
        ".Net Developer & Full Stack Developer & Full Stack Application Developer & .Net Software Engineer",
        "Big Data Developer & Java Developer",
        "Senior Software Developer - Java",
        "Swiggy Full Stack Developer - SDE I",
        "Java Developer & Software Engineer",
        "Python Developer",
        "Big Data Developer &  Full Stack Developer",
        "Senior Software Engineer - Java",
        "Python",
        "Sql Relational Database",
        "Senior Software Developer - Java & J2ee & UI Developer",
      ],
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: false,
        degree_mentioned: false,
        degree_preferred: false,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {
        Qualifications: [
          "Python, React, Linux, Unix, API",
          "Strong development experience using Python, REST API Service",
          "Database development skills, experience with Object-oriented and Relational databases - SQL Server/Oracle/Sybase",
          "Experience developing software using Agile methodology",
          "Knowledge of JIRA tools and Continuous Integration capabilities",
          "Hands on experience in writing unit and UI integration test cases",
        ],
      },
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113200",
      job_onet_job_zone: "4",
      job_occupational_categories: ["Developer"],
      job_naics_code: "561311",
      job_naics_name: "Employment Placement Agencies",
      estimated_salaries: [],
      apply_options: [],
      employer_reviews: [
        {
          publisher: "Glassdoor",
          employer_name: "TEKsystems",
          score: 4,
          num_stars: 4,
          review_count: 10056,
          max_score: 5,
          reviews_link:
            "https://www.glassdoor.com/Reviews/TEKsystems-Reviews-E23297.htm?utm_campaign=google_jobs_reviews&utm_source=google_jobs_reviews&utm_medium=organic",
        },
        {
          publisher: "Indeed",
          employer_name: "TEKsystems",
          score: 3.8,
          num_stars: 4,
          review_count: 4118,
          max_score: 5,
          reviews_link:
            "https://www.indeed.com/cmp/TEKsystems/reviews?utm_campaign=google_jobs_reviews&utm_source=google_jobs_reviews&utm_medium=organic",
        },
        {
          publisher: "CareerBliss",
          employer_name: "TEKsystems",
          score: 3.9,
          num_stars: 4,
          review_count: 405,
          max_score: 5,
          reviews_link:
            "https://www.careerbliss.com/teksystems/reviews/?utm_campaign=google_jobs_reviews&utm_source=google_jobs_reviews&utm_medium=organic",
        },
      ],
    },
  ],
} as const;

export const jobSearchResponse = {
  status: "OK",
  request_id: "36b4cbde-b0dc-4de8-8f41-ab46c5639a74",
  parameters: {
    query: "python developer in texas, usa",
    page: 1,
    num_pages: 1,
  },
  data: [
    {
      employer_name: "ConnectedX Inc.",
      employer_logo:
        "https://media.licdn.com/dms/image/C510BAQHwykuVgwslIQ/company-logo_200_200/0/1541167391398/connectedxinc_logo?e=2147483647&v=beta&t=uTyt_fsYcIs5zxsd0JqjJCrvqb5DLJf3jpUI09BkYMo",
      employer_website: "https://www.connectedxinc.com",
      employer_company_type: null,
      job_publisher: "LinkedIn",
      job_id: "hKYz5kO97LJug0moAAAAAA==",
      job_employment_type: "CONTRACTOR",
      job_title: "Python Developer",
      job_apply_link:
        "https://www.linkedin.com/jobs/view/python-developer-at-connectedx-inc-3760214352",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.6823,
      apply_options: [
        {
          publisher: "LinkedIn",
          apply_link:
            "https://www.linkedin.com/jobs/view/python-developer-at-connectedx-inc-3760214352",
          is_direct: false,
        },
      ],
      job_description:
        "ConnectedX is focused on Digital Transformation and Product Engineering Services, enabling clients achieve their business, operating and technology needs for the digital age. Our unique industry-based, consultative approach helps clients implement digital transformation initiatives. Headquartered in Dallas, Texas, U.S. ConnectedX is a preferred partner for leading Fortune 1000 enterprises and is consistently admired by the clients and employees across the globe.\n\nOur Direct Client in Texas is looking for\n\nJob Title: Python Developer\n\nLocation: Plano, Texas\n\nJob Description:\n\nWe are seeking a talented and experienced Python Developer to join our dynamic team in Plano, Texas. As a Python Developer in the automotive domain, you will play a crucial role in developing and maintaining software solutions that power our innovative automotive technologies.\n\nResponsibilities:\n• Collaborate with cross-functional teams, including software engineers, hardware engineers, and domain experts, to design and implement Python-based solutions for automotive applications.\n• Develop and maintain robust and scalable backend services and APIs that integrate with various automotive systems and components.\n• Work closely with product managers and stakeholders to understand and translate business requirements into technical specifications.\n• Participate in the entire software development lifecycle, from concept and design to testing, deployment, and maintenance.\n• Conduct code reviews, identify areas for improvement, and ensure high-quality code standards are met.\n• Stay current with industry trends, emerging technologies, and best practices to continuously enhance software development processes.\n\nQualifications:\n• Bachelor's degree in computer science, Software Engineering, or a related field.\n• Proven experience as a Python Developer, with a strong focus on backend development.\n• Solid understanding of software development principles, data structures, and algorithms.\n• Experience in the automotive domain is highly desirable, with knowledge of automotive systems, protocols, and standards.\n• Proficiency in Python and relevant frameworks (e.g., Django, Flask).\n• Familiarity with database systems such as SQL and NoSQL.\n• Strong problem-solving skills and the ability to work in a collaborative team environment.\n• Excellent communication skills, with the ability to convey technical concepts to both technical and non-technical stakeholders.\n\nAdditional Skills (Preferred):\n• Knowledge of real-time operating systems (RTOS) and embedded systems.\n• Experience with version control systems (e.g., Git) and continuous integration/continuous deployment (CI/CD) pipelines.\n• Familiarity with cybersecurity principles in the automotive context.\n• Understanding of agile development methodologies.\n\nHow to Apply:\n\nInterested candidates are invited to submit their resume, along with a cover letter highlighting their relevant experience and achievements.",
      job_is_remote: false,
      job_posted_at_timestamp: 1699559935,
      job_posted_at_datetime_utc: "2023-11-09T19:58:55.000Z",
      job_city: "Plano",
      job_state: "TX",
      job_country: "US",
      job_latitude: 33.019844,
      job_longitude: -96.69888,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=hKYz5kO97LJug0moAAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: "2023-12-09T19:58:55.000Z",
      job_offer_expiration_timestamp: 1702151935,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: null,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: true,
        degree_mentioned: true,
        degree_preferred: true,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {
        Qualifications: [
          "Bachelor's degree in computer science, Software Engineering, or a related field",
          "Proven experience as a Python Developer, with a strong focus on backend development",
          "Solid understanding of software development principles, data structures, and algorithms",
          "Proficiency in Python and relevant frameworks (e.g., Django, Flask)",
          "Familiarity with database systems such as SQL and NoSQL",
          "Strong problem-solving skills and the ability to work in a collaborative team environment",
          "Excellent communication skills, with the ability to convey technical concepts to both technical and non-technical stakeholders",
        ],
        Responsibilities: [
          "Collaborate with cross-functional teams, including software engineers, hardware engineers, and domain experts, to design and implement Python-based solutions for automotive applications",
          "Develop and maintain robust and scalable backend services and APIs that integrate with various automotive systems and components",
          "Work closely with product managers and stakeholders to understand and translate business requirements into technical specifications",
          "Participate in the entire software development lifecycle, from concept and design to testing, deployment, and maintenance",
          "Conduct code reviews, identify areas for improvement, and ensure high-quality code standards are met",
          "Stay current with industry trends, emerging technologies, and best practices to continuously enhance software development processes",
        ],
      },
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113200",
      job_onet_job_zone: "4",
    },
    {
      employer_name: "Ampstek",
      employer_logo:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPzj3pIQym93QfceALVLstkvrkGJ1tHQGTjS9j&s=0",
      employer_website: null,
      employer_company_type: null,
      job_publisher: "LinkedIn",
      job_id: "l76IcRktHL-RaprXAAAAAA==",
      job_employment_type: "FULLTIME",
      job_title: "Python Developer",
      job_apply_link:
        "https://www.linkedin.com/jobs/view/python-developer-at-ampstek-3752867709",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.6508,
      apply_options: [
        {
          publisher: "LinkedIn",
          apply_link:
            "https://www.linkedin.com/jobs/view/python-developer-at-ampstek-3752867709",
          is_direct: false,
        },
        {
          publisher: "Indeed",
          apply_link: "https://www.indeed.com/viewjob?jk=6bf20034f8d82455",
          is_direct: true,
        },
        {
          publisher: "Dice",
          apply_link:
            "https://www.dice.com/job-detail/343ca24b-d8a8-4a32-9062-a611259357f5",
          is_direct: true,
        },
        {
          publisher: "Python Jobs",
          apply_link:
            "https://pythonjob.xyz/job/2XuDQ6C0kgSG342mWBdbJ7DDkGY/Python%20Developer%20(Only%20Full%20time%20profiles)",
          is_direct: false,
        },
      ],
      job_description:
        "Job Title: Python Developer\n\nLocations: Fort Worth, TX-Hybrid\n\nJob Type: Full Time\n\nJob Description:\n\nMinimum 5 Years of relevant experience into Python\n\nStrong Python developer\n\nStrong communication and articulation skills\n\nUnderstanding requirements from business perspective instead of looking at it as a technical problem\n\nGood knowledge or experience in working with custom Python package management solutions like Nexus\n\nStrong knowledge in Python Flask and PostgreSQL database\n\nWorking knowledge of AWS – especially IAM, S3, Lambda and Python Boto3\n\nGood SDLC process – Git, testing, CI/CD etc.\n\nKnowledge on UI frameworks is a plus\n\nKnowledge of Databricks and data platforms is a plus\n\nThanks, and Regards\n\nSnehil Mishra\n\nsnehil@ ampstek.com\n\nlinkedin.com/in/snehil-mishra-1104b2154\n\nDesk-6093602673Extension-125\n\nwww.ampstek.com\n\nhttps://www.linkedin.com/company/ampstek/jobs/\n\nAmpstek – Global IT Partner\n\nRegistered Offices:\n\nNorth America and LATM: USA|Canada|Costa Rica|Mexico\n\nEurope:UK|Germany|France|Sweden|Denmark|Austria|Belgium|Netherlands|Romania|Poland|Czeh Republic|Bulgaria|Hungary|Ireland|Norway|Croatia|Slovakia|Portugal|Spain|Italy|Switzerland|Malta| Portugal\n\nAPAC:Australia|NZ|Singapore|Malaysia|South Korea|Hong Kong|Taiwan|Phillipines|Vietnam|Srilanka|India\n\nMEA :South Africa|UAE|Turkey|Egypt",
      job_is_remote: false,
      job_posted_at_timestamp: 1699461786,
      job_posted_at_datetime_utc: "2023-11-08T16:43:06.000Z",
      job_city: "Fort Worth",
      job_state: "TX",
      job_country: "US",
      job_latitude: 32.75549,
      job_longitude: -97.330765,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=l76IcRktHL-RaprXAAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: "2023-12-08T16:43:06.000Z",
      job_offer_expiration_timestamp: 1702053786,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: 60,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: true,
        degree_mentioned: false,
        degree_preferred: false,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {
        Qualifications: [
          "Minimum 5 Years of relevant experience into Python",
          "Strong Python developer",
          "Strong communication and articulation skills",
          "Understanding requirements from business perspective instead of looking at it as a technical problem",
          "Good knowledge or experience in working with custom Python package management solutions like Nexus",
          "Strong knowledge in Python Flask and PostgreSQL database",
          "Working knowledge of AWS – especially IAM, S3, Lambda and Python Boto3",
          "Good SDLC process – Git, testing, CI/CD etc",
        ],
      },
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113200",
      job_onet_job_zone: "4",
    },
    {
      employer_name: "SynergisticIT",
      employer_logo: null,
      employer_website: null,
      employer_company_type: null,
      job_publisher: "ZipRecruiter",
      job_id: "7oKm_SkxjLxpFtVuAAAAAA==",
      job_employment_type: "FULLTIME",
      job_title: "PYTHON DEVELOPER(ENTRY LEVEL)",
      job_apply_link:
        "https://www.ziprecruiter.com/c/SynergisticIT/Job/PYTHON-DEVELOPER(ENTRY-LEVEL)/-in-Austin,TX?jid=95b95b82c4f3b4bd",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.6714,
      apply_options: [
        {
          publisher: "ZipRecruiter",
          apply_link:
            "https://www.ziprecruiter.com/c/SynergisticIT/Job/PYTHON-DEVELOPER(ENTRY-LEVEL)/-in-Austin,TX?jid=95b95b82c4f3b4bd",
          is_direct: false,
        },
      ],
      job_description:
        "SynergisticIT is committed to fast track your career by increasing your career prospects. We provide a broad spectrum of career advancement solutions. Whether you are struggling to find a job or hustling to get noticed by the hiring managers, we can help you stand out in your professional endeavors.\nTrusted by thousands of tech enthusiasts, SynergisticIT can bridge your skill and knowledge gap to make you competent for high-tech jobs. Our invaluable business acumen helps us assist thriving job seekers in achieving their career goals.\nCurrently, we are looking for adept entry-level Python Developers to work with our elite group of clients, namely Client, PayPal, Expedia Group, Google, Apple, Cognizant, Ford, Cisco, Walmart Labs, etc.\n\nRequired Qualifications and Background\n• Bachelor's degree or Master's degree in Computer Science, Electrical Engineering, Computer Engineering, Information Systems, IT, Mathematics,\n• Mathematics or Statistics background\nSkills Required\n• 0 to 2 years of experience in Python development\n• Deep understanding of the software development life cycle\n• Knowledge of Linear Algebra, Statistics, and Mathematics concepts\n• Excellent written and verbal communication skills\n• Technically inquisitive, self-learner, team player, and highly motivated\n• Strong work ethics and creative problem-solving abilities\n\nPreferred Skills\n• Deep Learning\n• Data visualization\n• Scal\n• NLP\n• Django\nRoles and Responsibilities\ns an entry-level Python Developer, you need to perform the following duties:\n• Write server-side web application logic\n• Write scalable and effective codes in Python\n• Develop backend components to boost overall application's performance\n• Executing tests and fixing bugs in applications and software\n• Implement data protection and security solutions\n• Connect applications with third-party web services\n• Support frontend developers by integrating UI elements into Python applications\n\nBenefits\n• Competitive salary\n• Flexible work schedule & part-time off\n• E-verified\n• H1B Filing\n• No relocation\n• On job technical support\n• Skill Enhancement\n• Opportunity to work with Fortune 500 Companies\n\nWho can apply?\nThis job opportunity is best suited for recent IT graduates who want to make a mark in the tech industry and upskill their IT talent. Anyone with a basic knowledge of Python programming or having some experience in building Python software solutions can apply for this position.\nNo third-party candidates or c2c candidates\n\nIf you are interested, please apply to the posting.\n\nNo phone calls please, Shortlisted candidates would be reached out.",
      job_is_remote: false,
      job_posted_at_timestamp: 1626998400,
      job_posted_at_datetime_utc: "2021-07-23T00:00:00.000Z",
      job_city: "Austin",
      job_state: "TX",
      job_country: "US",
      job_latitude: 30.267153,
      job_longitude: -97.74306,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=7oKm_SkxjLxpFtVuAAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: "2023-12-09T00:00:00.000Z",
      job_offer_expiration_timestamp: 1702080000,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: null,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: false,
        degree_mentioned: true,
        degree_preferred: true,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: 65000,
      job_max_salary: 140000,
      job_salary_currency: "USD",
      job_salary_period: "YEAR",
      job_highlights: {
        Qualifications: [
          "Bachelor's degree or Master's degree in Computer Science, Electrical Engineering, Computer Engineering, Information Systems, IT, Mathematics,",
          "Mathematics or Statistics background",
          "0 to 2 years of experience in Python development",
          "Deep understanding of the software development life cycle",
          "Knowledge of Linear Algebra, Statistics, and Mathematics concepts",
          "Excellent written and verbal communication skills",
          "Technically inquisitive, self-learner, team player, and highly motivated",
          "Strong work ethics and creative problem-solving abilities",
          "Support frontend developers by integrating UI elements into Python applications",
        ],
        Responsibilities: [
          "Write server-side web application logic",
          "Write scalable and effective codes in Python",
          "Develop backend components to boost overall application's performance",
          "Executing tests and fixing bugs in applications and software",
          "Implement data protection and security solutions",
          "Connect applications with third-party web services",
        ],
        Benefits: [
          "Competitive salary",
          "Flexible work schedule & part-time off",
          "No relocation",
          "On job technical support",
          "Opportunity to work with Fortune 500 Companies",
        ],
      },
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113200",
      job_onet_job_zone: "4",
      job_occupational_categories: [
        "15-1132.00: Software Developers, Applications",
      ],
    },
    {
      employer_name: "Nzyme Inc.",
      employer_logo:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPd-hps7yHu6ZmQPwa8QzKacpqKLbzwCNNoBVY&s=0",
      employer_website: null,
      employer_company_type: null,
      job_publisher: "OPTnation",
      job_id: "T4GRNbO47j6wMONJAAAAAA==",
      job_employment_type: "FULLTIME",
      job_title: "Entry level python developer",
      job_apply_link:
        "https://www.optnation.com/entry-level-python-developer-job-in-texas-city-tx-view-jobid-23498",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.6698,
      apply_options: [
        {
          publisher: "OPTnation",
          apply_link:
            "https://www.optnation.com/entry-level-python-developer-job-in-texas-city-tx-view-jobid-23498",
          is_direct: false,
        },
      ],
      job_description:
        "JOB DESCRIPTION You will develop software using Python PostgreSQL and Flask to improve the performance of enterprise websites with millions of pages. You will architect analyze develop version control code review and deploy Python. EDUCATION & EXPERIENCE Bachelor&39;s or master’s degree in Computer Science or related subject. 0-2 years’ experience or coursework developing Python-based software with a database (PostgreSQL or other) and a framework (Django Flask or other) REQUIRED SKILLS APIs and web-service integration Familiar with version control systems (Git/GitHub or Subversion) Familiar with testing and debugging code Ability to work autonomously; self-disciplined Ability to communicate technical requirements to business teams and translate business requirements into technical requirements. RESPONSIBILITIES Develop test debug and document Python applications that utilize Python and Flask. Utilize GitHub and Docker environment to develop and deploy code Develop microservices using Python that will serve data to other products within the company Create SQL scripts/stored procedures and troubleshoot them in PostgreSQL Ability to refactor portions of an existing product currently implemented in Python Perl and PostgreSQL Maintaining detailed requirements/design/technical documentation for new and existing components Complete work within deadlines.",
      job_is_remote: false,
      job_posted_at_timestamp: 1677196800,
      job_posted_at_datetime_utc: "2023-02-24T00:00:00.000Z",
      job_city: "Texas City",
      job_state: "TX",
      job_country: "US",
      job_latitude: 29.383844,
      job_longitude: -94.9027,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=T4GRNbO47j6wMONJAAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: null,
      job_offer_expiration_timestamp: null,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: null,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: [
        "Python",
        "Django",
        "Flask",
        "SQL",
        "HTML",
        "CSS3",
        "DBMS",
      ],
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: false,
        degree_mentioned: true,
        degree_preferred: true,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: 70000,
      job_max_salary: 94000,
      job_salary_currency: "USD",
      job_salary_period: "YEAR",
      job_highlights: {},
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113200",
      job_onet_job_zone: "4",
    },
    {
      employer_name: "SynergisticIT",
      employer_logo:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-UrAK1LCetSvno8PT3nMB4vJV4VdEEPN7PrgC&s=0",
      employer_website: null,
      employer_company_type: null,
      job_publisher: "LinkedIn",
      job_id: "diarenuUzQgtpLz1AAAAAA==",
      job_employment_type: "PARTTIME",
      job_title: "Python Developer (Entry Level)",
      job_apply_link:
        "https://www.linkedin.com/jobs/view/python-developer-entry-level-at-synergisticit-3664610954",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.687,
      apply_options: [
        {
          publisher: "LinkedIn",
          apply_link:
            "https://www.linkedin.com/jobs/view/python-developer-entry-level-at-synergisticit-3664610954",
          is_direct: false,
        },
        {
          publisher: "ZipRecruiter",
          apply_link:
            "https://www.ziprecruiter.com/c/SynergisticIT/Job/Python-Developer-(Entry-Level)/-in-Dallas,TX?jid=c42bdc40190a6c76",
          is_direct: false,
        },
        {
          publisher: "Expertini",
          apply_link:
            "https://us.expertini.com/jobs/job/python-developer-entry-level--dallas-texas-synergisticit-126472521/",
          is_direct: false,
        },
        {
          publisher: "Search American Jobs",
          apply_link:
            "https://searchamericanjobs.com/job/python-developer-entry-level--dallas-texas-synergisticit-126472521/",
          is_direct: false,
        },
      ],
      job_description:
        "SynergisticIT is committed to fast track your career by increasing your career prospects. We provide a broad spectrum of career advancement solutions. Whether you are struggling to find a job or hustling to get noticed by the hiring managers, we can help you stand out in your professional endeavors.\n\nTrusted by thousands of tech enthusiasts, SynergisticIT can bridge your skill and knowledge gap to make you competent for high-tech jobs. Our invaluable business acumen helps us assist thriving job seekers in achieving their career goals.\n\nCurrently, we are looking for adept entry-level Python Developers to work with our elite group of clients, namely Client, PayPal, Expedia Group, Google, Apple, Cognizant, Ford, Cisco, Walmart Labs, etc.\n\nRequired Qualifications And Background\n• Bachelor's degree or Master's degree in Computer Science, Electrical Engineering, Computer Engineering, Information Systems, IT, Mathematics,\n• Mathematics or Statistics background\n\nSkills Required\n• 0 to 2 years of experience in Python development\n• Deep understanding of the software development life cycle\n• Knowledge of Linear Algebra, Statistics, and Mathematics concepts\n• Excellent written and verbal communication skills\n• Technically inquisitive, self-learner, team player, and highly motivated\n• Strong work ethics and creative problem-solving abilities\n\nPreferred Skills\n• Deep Learning\n• Data visualization\n• Scala\n• NLP\n• Django\n\nRoles and Responsibilities\n\nAs an entry-level Python Developer, you need to perform the following duties:\n• Write server-side web application logic\n• Write scalable and effective codes in Python\n• Develop backend components to boost overall application's performance\n• Executing tests and fixing bugs in applications and software\n• Implement data protection and security solutions\n• Connect applications with third-party web services\n• Support frontend developers by integrating UI elements into Python applications\n\nBenefits\n• Competitive salary\n• Flexible work schedule & part-time off\n• E-verified\n• H1B Filing\n• No relocation\n• On job technical support\n• Skill Enhancement\n• Opportunity to work with Fortune 500 Companies\n\nWho can apply?\n\nThis job opportunity is best suited for recent IT graduates who want to make a mark in the tech industry and upskill their IT talent. Anyone with a basic knowledge of Python programming or having some experience in building Python software solutions can apply for this position.\n\nCandidate's Outcome : Best Programmers in USA | Best Coding Bootcamp - SynergisticIT\n\nNo third-party candidates or c2c candidates\n\nIf you are interested, please apply to the posting.\n\nNo phone calls please, Shortlisted candidates would be reached out.",
      job_is_remote: false,
      job_posted_at_timestamp: 1689661486,
      job_posted_at_datetime_utc: "2023-07-18T06:24:46.000Z",
      job_city: "Dallas",
      job_state: "TX",
      job_country: "US",
      job_latitude: 32.776665,
      job_longitude: -96.79699,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=diarenuUzQgtpLz1AAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: "2023-12-04T03:56:04.000Z",
      job_offer_expiration_timestamp: 1701662164,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: null,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: true,
        degree_mentioned: true,
        degree_preferred: true,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {
        Qualifications: [
          "Bachelor's degree or Master's degree in Computer Science, Electrical Engineering, Computer Engineering, Information Systems, IT, Mathematics,",
          "Mathematics or Statistics background",
          "0 to 2 years of experience in Python development",
          "Deep understanding of the software development life cycle",
          "Knowledge of Linear Algebra, Statistics, and Mathematics concepts",
          "Excellent written and verbal communication skills",
          "Technically inquisitive, self-learner, team player, and highly motivated",
          "Strong work ethics and creative problem-solving abilities",
          "Support frontend developers by integrating UI elements into Python applications",
        ],
        Responsibilities: [
          "As an entry-level Python Developer, you need to perform the following duties:",
          "Write server-side web application logic",
          "Write scalable and effective codes in Python",
          "Develop backend components to boost overall application's performance",
          "Executing tests and fixing bugs in applications and software",
          "Implement data protection and security solutions",
          "Connect applications with third-party web services",
        ],
        Benefits: [
          "Competitive salary",
          "Flexible work schedule & part-time off",
          "No relocation",
          "On job technical support",
          "Opportunity to work with Fortune 500 Companies",
        ],
      },
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113200",
      job_onet_job_zone: "4",
    },
    {
      employer_name: "SynergisticIT",
      employer_logo: null,
      employer_website: null,
      employer_company_type: null,
      job_publisher: "ZipRecruiter",
      job_id: "_2zrRnwarpf3YwwEAAAAAA==",
      job_employment_type: "FULLTIME",
      job_title: "Entry Level Python Developer",
      job_apply_link:
        "https://www.ziprecruiter.com/c/SynergisticIT/Job/Entry-Level-Python-Developer/-in-Houston,TX?jid=b5db608a2de13d7e",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.5731,
      apply_options: [
        {
          publisher: "ZipRecruiter",
          apply_link:
            "https://www.ziprecruiter.com/c/SynergisticIT/Job/Entry-Level-Python-Developer/-in-Houston,TX?jid=b5db608a2de13d7e",
          is_direct: false,
        },
        {
          publisher: "BeBee",
          apply_link:
            "https://us.bebee.com/job/20231027-eb1fb84cb35560553e71ea0192bd45f1",
          is_direct: false,
        },
        {
          publisher: "Trabajo.org",
          apply_link:
            "https://us.trabajo.org/job-835-20231021-7e8d09b4a263aa6966de4b991d875608",
          is_direct: false,
        },
        {
          publisher: "Jobrapido.com",
          apply_link: "https://us.jobrapido.com/jobpreview/3024201977",
          is_direct: false,
        },
        {
          publisher: "Jobilize",
          apply_link:
            "https://www.jobilize.com/job/us-tx-houston-entry-level-python-developer-synergisticit-hiring-now",
          is_direct: false,
        },
      ],
      job_description:
        "About Us:\nSynergistic IT is a full-service staffing and placement firm servicing client in America for the past 12+ years. We are dedicated towards fulfilling the IT needs of our clients. From staffing to full implementation of projects we provide the highest quality IT Services. We Intend to deliver exceptional student outcome. We don't just help you secure a tech job but build a solid career in technology.\n\nJob Description:\n• Should know how to work in large verities of libraries, frameworks, and modules\n• Duck typing, string, tuple and Lambda knowledge required\n• Django Frame work required\n• Worked on Django model, CBV, Django CRUD operation\n\nSkills Required-\n• Knowledge of Python web frameworks and event-driven programming in Python.\n• Basic understanding of front-end technologies.\n• High attention to detail.\n• Excellent communication and problem-solving skills.\n• Proficient understanding of code versioning tools\n• Know the classes of SCALA, Traits of SCALA, and Collection of SCALA\n\nEducation Requirement: -\nBachelors, Masters in Computer Science/ Computer Engineering/ Information Systems/Information Technology/ Electrical Engineering/ Mechanical Engineering.\n\nBenefits:\n• On Job Technical support\n• E- verified\n• Help to get H1B Employer.\n• Full time position\n\nCandidate who are missing the required skills, might be provided an option to enhance their skills, so that they can also apply for the role and can make a career in IT industry.\n\nIf you do respond via e-mail, please include a daytime phone number so that we can reach you. In considering candidates, time is of the essence, so please respond ASAP. Thank you",
      job_is_remote: false,
      job_posted_at_timestamp: 1670227200,
      job_posted_at_datetime_utc: "2022-12-05T08:00:00.000Z",
      job_city: "Houston",
      job_state: "TX",
      job_country: "US",
      job_latitude: 29.760427,
      job_longitude: -95.369804,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=_2zrRnwarpf3YwwEAAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: "2023-12-10T00:00:00.000Z",
      job_offer_expiration_timestamp: 1702166400,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: null,
        experience_mentioned: false,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: false,
        degree_mentioned: true,
        degree_preferred: false,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {
        Qualifications: [
          "Knowledge of Python web frameworks and event-driven programming in Python",
          "Basic understanding of front-end technologies",
          "High attention to detail",
          "Excellent communication and problem-solving skills",
          "Proficient understanding of code versioning tools",
          "Know the classes of SCALA, Traits of SCALA, and Collection of SCALA",
          "Bachelors, Masters in Computer Science/ Computer Engineering/ Information Systems/Information Technology/ Electrical Engineering/ Mechanical Engineering",
        ],
        Responsibilities: [
          "Should know how to work in large verities of libraries, frameworks, and modules",
          "Django Frame work required",
          "Worked on Django model, CBV, Django CRUD operation",
        ],
        Benefits: ["On Job Technical support", "Full time position"],
      },
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113200",
      job_onet_job_zone: "4",
      job_occupational_categories: [
        "15-1132.00: Software Developers, Applications",
      ],
    },
    {
      employer_name: "SynergisticIT",
      employer_logo:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-UrAK1LCetSvno8PT3nMB4vJV4VdEEPN7PrgC&s=0",
      employer_website: null,
      employer_company_type: null,
      job_publisher: "LinkedIn",
      job_id: "Qij9hErsTLNHStu0AAAAAA==",
      job_employment_type: "CONTRACTOR",
      job_title: "Entry Level Python Developer",
      job_apply_link:
        "https://www.linkedin.com/jobs/view/entry-level-python-developer-at-synergisticit-3697723693",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.687,
      apply_options: [
        {
          publisher: "LinkedIn",
          apply_link:
            "https://www.linkedin.com/jobs/view/entry-level-python-developer-at-synergisticit-3697723693",
          is_direct: false,
        },
        {
          publisher: "世界門",
          apply_link:
            "https://www.sekaimon.com.tw/daigonew?url=https%3A%2F%2Fwww.linkedin.com%2Fjobs%2Fview%2Fentry-level-python-developer-at-synergisticit-3697723693%3FrefId%3DS1ihYsN77gz9PSbCcOhX6w%253D%253D%26trackingId%3DIULeyeJPm6nbhb4AjCwyVQ%253D%253D%26trk%3Dpublic_jobs_people-also-viewed",
          is_direct: false,
        },
        {
          publisher: "BeBee",
          apply_link:
            "https://us.bebee.com/job/20231101-140a2964053ab779028745a5bec6b814",
          is_direct: false,
        },
        {
          publisher: "Trabajo.org",
          apply_link:
            "https://us.trabajo.org/job-2003-20231103-aea3e058493ddeffc632e8f85035df05",
          is_direct: false,
        },
        {
          publisher: "Jobrapido.com",
          apply_link: "https://us.jobrapido.com/jobpreview/3025704841",
          is_direct: false,
        },
      ],
      job_description:
        "SYNERGISTICIT is aware that the Job Market is Challenging because of Tech Layoffs due to which The Job market is flooded with hundreds and thousands of laid off Jobseekers who are competing with existing Jobseekers. For entry level Job seekers to get client interviews and jobs they need to differentiate themselves by ensuring they have exceptional skills and technologies to be noticed by clients.\n\nSince 2010 we have helped Jobseekers differentiate themselves by providing the clients with candidates who have the requisite skills and experience to outperform at interviews and clients. Here at SynergisticIT We just don't focus on getting you a Job we make careers. All Positions are open for all visas and US citizens We at Synergisticit understand the problem of the mismatch between employer's requirements and Employee skills and that's why since 2010 we have helped thousands of candidates get jobs at technology clients like apple, google, Paypal, western union, Client, visa, walmart labs etc to name a few. We have an excellent reputation with the clients. Currently, We are looking for entry-level software programmers, Java Full stack developers, Python/Java developers, Data analysts/ Data Scientists, Machine Learning engineers. Who Should Apply Recent Computer science/Engineering /Mathematics/Statistics or Science Graduates looking to make their careers in IT Industry We welcome candidates with all visas and citizens to apply. We assist in filing for STEM extension and also for H1b and Green card filing to Candidates\n\nWe also offer Skill enhancement programs for candidates who are either missing skills or are lacking Industry/Client experience with Projects and skills. Candidates having difficulty in finding jobs or cracking interviews or who wants to improve their skill portfolio. If they are qualified with enough skills and have hands on project work at clients then no need for skill enhancement.\n\nCandidates can benefit from skill enhancement if they fall into the below categories.\n\nCandidates who Lack Experience or are freshers with No actual on Job experience with projects with clients Have had a break in careers Lack Technical Competency or skills being demanded by clients Different visa candidates (Like OPT/H4EAD/L2EAD )who want to get employed and settle down in the USA please check the below links to see success outcomes of our candidates https://www.synergisticit.com/candidate-outcomes/\n\nWatch the below videos of us participating at Industry events with the Top companies in Technology at Oracle Cloud world /Oracle Java one (Las vegas) and at Gartner Data Analytics Summit (Florida)\n\nOracle CloudWorld Event (OCW) Las Vegas 2022 | SynergisticIT - YouTube https://www.youtube.com/watch?v=OAFOhcGy9Z8\n\nhttps://www.youtube.com/watch?v=EmO7NrWHkLM https://www.youtube.com/watch?v=NVBU9RYZ6UI\n\nhttps://www.youtube.com/watch?v=Yy74yvjatVg SynergisticIT at Gartner Data and Analytics Summit 2023 - YouTube\n\nhttps://www.synergisticit.com/java-track/ https://www.synergisticit.com/data-science-track/ https://www.synergisticit.com/contact-us/\n\nIf you have relevant skills and industry experience, please apply if not then candidates can opt for Skill enhancement.\n\nFor getting help with interviews please visit\n\nhttps://www.synergisticit.com/interview-questions/\n\nREQUIRED SKILLS For Java /Software Programmers\n• Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT\n• Highly motivated, self-learner, and technically inquisitive\n• Experience in programming language Java and understanding of the software development life cycle\n• Project work on the skills\n• Knowledge of Core Java , javascript , C++ or software programming\n• Spring boot, Microservices, Docker, Jenkins and REST API's experience\n• Excellent written and verbal communication skills\n\nFor data Science/Machine learning\n\nRequired Skills\n• Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT\n• Project work on the technologies needed\n• Highly motivated, self-learner, and technically inquisitive\n• Experience in programming language Java and understanding of the software development life cycle\n• Knowledge of Statistics, SAS, Python, Computer Vision, data visualization tools\n• Excellent written and verbal communication skills\n\nPreferred skills: NLP, Text mining, Tableau, PowerBI, Time series analysis\n\nPlease understand skills and relevant experience on real world projects are required by clients for selection even if its Junior or entry level position the additional skills and Project work with hands on experience building projects at client site are the only way a candidate can be picked by clients. If not having the skills or hands on project work at client site then candidates can opt for skill enhancement to gain the required skills and project work. No third party candidates or c2c candidates\n\nplease only apply to the posting\n\nNo phone calls please. Shortlisted candidates would be reached out.",
      job_is_remote: false,
      job_posted_at_timestamp: 1690843929,
      job_posted_at_datetime_utc: "2023-07-31T22:52:09.000Z",
      job_city: "Arlington",
      job_state: "TX",
      job_country: "US",
      job_latitude: 32.735687,
      job_longitude: -97.10806,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=Qij9hErsTLNHStu0AAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: "2023-12-04T03:56:06.000Z",
      job_offer_expiration_timestamp: 1701662166,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: null,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: true,
        degree_mentioned: true,
        degree_preferred: true,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {
        Qualifications: [
          "REQUIRED SKILLS For Java /Software Programmers",
          "Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT",
          "Highly motivated, self-learner, and technically inquisitive",
          "Experience in programming language Java and understanding of the software development life cycle",
          "Knowledge of Core Java , javascript , C++ or software programming",
          "Spring boot, Microservices, Docker, Jenkins and REST API's experience",
          "Excellent written and verbal communication skills",
          "For data Science/Machine learning",
          "Project work on the technologies needed",
          "Knowledge of Statistics, SAS, Python, Computer Vision, data visualization tools",
          "Please understand skills and relevant experience on real world projects are required by clients for selection even if its Junior or entry level position the additional skills and Project work with hands on experience building projects at client site are the only way a candidate can be picked by clients",
          "If not having the skills or hands on project work at client site then candidates can opt for skill enhancement to gain the required skills and project work",
        ],
      },
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113200",
      job_onet_job_zone: "4",
    },
    {
      employer_name: "Collabera",
      employer_logo:
        "https://collabera.com/wp-content/uploads/2022/06/Mask-group-2.svg",
      employer_website: "http://www.collabera.com",
      employer_company_type: "Computer Services",
      job_publisher: "Professional Diversity Network",
      job_id: "U4uyXrHXSgVVPyRtAAAAAA==",
      job_employment_type: "TEMPORARY",
      job_title: "Python Developer",
      job_apply_link:
        "https://www.prodivnet.com/job/python-developer-fort-worth-texas-13849525",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.6766,
      apply_options: [
        {
          publisher: "Professional Diversity Network",
          apply_link:
            "https://www.prodivnet.com/job/python-developer-fort-worth-texas-13849525",
          is_direct: false,
        },
        {
          publisher: "Ladders",
          apply_link:
            "https://www.theladders.com/job-listing/python-developer-collabera-fort-worth-tx-_v2_-7-3304606151.html",
          is_direct: false,
        },
      ],
      job_description:
        "Title: Python Developer\nLocation: Fort Worth, Texas\nDuration: 6 months + extensions\n\nMust Haves:\n• 5+ years of professional experience as a Python Developer, with a focus on complex programming, code testing, and debugging Python code\n• Experience developing RESTful APIs in Python\n• 5+ years in Python programming language and its libraries/frameworks (e.g., Django, Flask)\n• Experience integrating Python applications with third-party web services, APIs, and databases\n• Practical knowledge of front-end technologies, including JavaScript, HTML, and CSS\n• Familiarity with version control systems, particularly GitHub, and experience configuring workflows\n• Certification in Python programming (PCEP, PCAP, PCPP, CEPP)\n• Desire/ability to mentor junior developers and serve as Python SME\n\nPDN-9a8950f9-b8f1-4193-b40f-9817efea0c8d",
      job_is_remote: false,
      job_posted_at_timestamp: 1699161996,
      job_posted_at_datetime_utc: "2023-11-05T05:26:36.000Z",
      job_city: "Fort Worth",
      job_state: "TX",
      job_country: "US",
      job_latitude: 32.75549,
      job_longitude: -97.330765,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=U4uyXrHXSgVVPyRtAAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: "2024-02-03T06:26:36.000Z",
      job_offer_expiration_timestamp: 1706941596,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: 60,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: false,
        degree_mentioned: false,
        degree_preferred: false,
        professional_certification_mentioned: true,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {
        Qualifications: [
          "5+ years of professional experience as a Python Developer, with a focus on complex programming, code testing, and debugging Python code",
          "Experience developing RESTful APIs in Python",
          "5+ years in Python programming language and its libraries/frameworks (e.g., Django, Flask)",
          "Experience integrating Python applications with third-party web services, APIs, and databases",
          "Practical knowledge of front-end technologies, including JavaScript, HTML, and CSS",
          "Familiarity with version control systems, particularly GitHub, and experience configuring workflows",
          "Certification in Python programming (PCEP, PCAP, PCPP, CEPP)",
          "Desire/ability to mentor junior developers and serve as Python SME",
        ],
      },
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113200",
      job_onet_job_zone: "4",
      job_naics_code: "541511",
      job_naics_name: "Custom Computer Programming Services",
    },
    {
      employer_name: "Drive Capital",
      employer_logo:
        "https://www.gran-turismo.com/gtsport/decal/6269020581755093512_1.png",
      employer_website: "http://www.drivecapital.com",
      employer_company_type: "Finance",
      job_publisher: "BeBee",
      job_id: "NBvbD9THUVNvyWjaAAAAAA==",
      job_employment_type: "FULLTIME",
      job_title: "Staff Software Engineer Python",
      job_apply_link:
        "https://us.bebee.com/job/20231110-e10b74968abf685fbae27f316e419d8c",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.501,
      apply_options: [
        {
          publisher: "BeBee",
          apply_link:
            "https://us.bebee.com/job/20231110-e10b74968abf685fbae27f316e419d8c",
          is_direct: false,
        },
      ],
      job_description:
        "At Torc, we have always believed that autonomous vehicle technology will transform how we travel, move freight, and do business.\n\nA leader in autonomous driving since 2007, Torc has spent over a decade commercializing our solutions with experienced partners.\n\nNow a part of the Daimler family, we are focused solely on developing software for automated trucks to transform how the world moves freight.\n\nJoin us and catapult your career with the company that helped pioneer autonomous technology, and the first AV software company with the vision to partner directly with a truck manufacturer.\nYou will support the testing of our autonomous trucks in a virtual testing environment. Focus is the testing of our perception system.\n\nIn this role, you will be responsible for supporting our software, systems, and release teams in the execution of virtual testing of Torc's software components and integrated autonomous driving systems.\nDevelop, design, test, implement, document and modify simulation technologies and methods as well as identify, debug, and resolve technical problems in the perception sensor simulation environment\nAdvance the perception sensor simulation environment with modern augmentation and ML methods to overcome the domain gap between real world data and synthetic simulation data\nIdentify and apply appropriate virtual testing technologies and methodologies for a given perception component or system-level testing effort\nSupport log data replay and metrics development for perception software components\nIdentify and document use cases and implement prototypes for each use case and assist with the transition and training of these cases to software teams\nIdentify testing gaps and derive requirements for new or improved test tools, perception simulation environments and test frameworks\nMaster's degree in Computer Science, Computer Engineering, Robotics Engineering, Systems Engineering, or engineering equivalent.\n~7+ years of software development experience\n~2+ years of software systems integration and testing experience\n~ Full life cycle software development including unit and software integration testing and configuration management. Experience applying machine learning or neural rendering techniques to simulation\n~ Programming experience in C++ and using Python for data analysis\n~ Experiences with Software-in-the-Loop (SIL) simulation and testing methodologies\n~ Proficiency with programming under Linux and Linux command line functions\n~ Ability to lead virtual testing events within specific areas of system, tracing and troubleshooting the entire software stack\n~ Experience reporting to product and quality management on testing progress\n\nExperience with machine learning, neural rendering techniques, or data augmentation for autonomous applications\nKanban, Scrum or Scaled Agile development\nExperience developing sensor models, 3D simulation environments, rendering and ray tracing in a perception simulation environment (i.e., game engine or other similar simulation environment)\nSoftware and system troubleshooting and problem-solving with specific focus on system-level analysis, fault isolation and identification\nAutomotive or similar test and validation\nPerks of Being a Full-time Torc'r\nA competitive compensation package that includes a bonus component and stock options\n~100% paid medical, dental, and vision premiums for full-time employees\n~Flexibility in schedule and generous paid vacation (available immediately after start date)\n~ Company-wide holiday office closures\n~ At Torc, we're committed to building a diverse and inclusive workplace. We celebrate the uniqueness of our Torc'rs and do not discriminate based on race, religion, color, national origin, gender (including pregnancy, childbirth, or related medical conditions), sexual orientation, gender identity, gender expression, age, veteran status, or disabilities.",
      job_is_remote: false,
      job_posted_at_timestamp: 1699621589,
      job_posted_at_datetime_utc: "2023-11-10T13:06:29.000Z",
      job_city: "Austin",
      job_state: "TX",
      job_country: "US",
      job_latitude: 30.267153,
      job_longitude: -97.74306,
      job_benefits: ["dental_coverage", "paid_time_off", "health_insurance"],
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=NBvbD9THUVNvyWjaAAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: "2023-11-18T00:00:00.000Z",
      job_offer_expiration_timestamp: 1700265600,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: 84,
        experience_mentioned: true,
        experience_preferred: false,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: false,
        degree_mentioned: true,
        degree_preferred: true,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {
        Qualifications: [
          "Master's degree in Computer Science, Computer Engineering, Robotics Engineering, Systems Engineering, or engineering equivalent",
          "~7+ years of software development experience",
          "~2+ years of software systems integration and testing experience",
          "~ Full life cycle software development including unit and software integration testing and configuration management",
          "Experience applying machine learning or neural rendering techniques to simulation",
          "~ Programming experience in C++ and using Python for data analysis",
          "~ Experiences with Software-in-the-Loop (SIL) simulation and testing methodologies",
          "~ Proficiency with programming under Linux and Linux command line functions",
          "~ Ability to lead virtual testing events within specific areas of system, tracing and troubleshooting the entire software stack",
          "~ Experience reporting to product and quality management on testing progress",
          "Experience with machine learning, neural rendering techniques, or data augmentation for autonomous applications",
          "Kanban, Scrum or Scaled Agile development",
          "Experience developing sensor models, 3D simulation environments, rendering and ray tracing in a perception simulation environment (i.e., game engine or other similar simulation environment)",
          "Software and system troubleshooting and problem-solving with specific focus on system-level analysis, fault isolation and identification",
          "Automotive or similar test and validation",
        ],
        Responsibilities: [
          "In this role, you will be responsible for supporting our software, systems, and release teams in the execution of virtual testing of Torc's software components and integrated autonomous driving systems",
          "Develop, design, test, implement, document and modify simulation technologies and methods as well as identify, debug, and resolve technical problems in the perception sensor simulation environment",
          "Advance the perception sensor simulation environment with modern augmentation and ML methods to overcome the domain gap between real world data and synthetic simulation data",
          "Identify and apply appropriate virtual testing technologies and methodologies for a given perception component or system-level testing effort",
          "Support log data replay and metrics development for perception software components",
          "Identify and document use cases and implement prototypes for each use case and assist with the transition and training of these cases to software teams",
          "Identify testing gaps and derive requirements for new or improved test tools, perception simulation environments and test frameworks",
        ],
        Benefits: [
          "A competitive compensation package that includes a bonus component and stock options",
          "~100% paid medical, dental, and vision premiums for full-time employees",
          "~Flexibility in schedule and generous paid vacation (available immediately after start date)",
        ],
      },
      job_job_title: "Software engineer",
      job_posting_language: "en",
      job_onet_soc: "15113200",
      job_onet_job_zone: "4",
      job_naics_code: "523920",
      job_naics_name: "Portfolio Management",
    },
    {
      employer_name: "Company Name",
      employer_logo:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRozpyZ2-Blq6K0b_7uk1IBsPMU6UbpYVLrjwqL&s=0",
      employer_website: null,
      employer_company_type: null,
      job_publisher: "Radley James",
      job_id: "ZLHPTnm0vUZhlFhdAAAAAA==",
      job_employment_type: "FULLTIME",
      job_title: "Python Developer – Houston, TX (Hybrid)",
      job_apply_link:
        "https://www.radleyjames.com/job/python-developer-houston-tx-hybrid/",
      job_apply_is_direct: false,
      job_apply_quality_score: 0.6809,
      apply_options: [
        {
          publisher: "Radley James",
          apply_link:
            "https://www.radleyjames.com/job/python-developer-houston-tx-hybrid/",
          is_direct: false,
        },
        {
          publisher: "BeBee",
          apply_link:
            "https://us.bebee.com/job/20231110-59e7943121249505982d53e747c55b0e",
          is_direct: false,
        },
        {
          publisher: "Jooble",
          apply_link:
            "https://jooble.org/jdp/8291217604751556103/Python-Developer-+-Houston%2C-TX-(Hybrid)-Houston%2C-TX",
          is_direct: false,
        },
        {
          publisher: "Jobilize",
          apply_link:
            "https://www.jobilize.com/job/us-tx-houston-python-developer-radley-james-hiring-now-job-immediately",
          is_direct: false,
        },
      ],
      job_description:
        "Python Developer\n\nHouston, Texas, United States (Hybrid)\n\nA leading hedge fund with a global reputation for being one of the best in the industry is looking to add a mid to senior developer to its Houston office.\n\nThis individual will be working on expanding their global analytics and trading-related tools and APIs, liaising between external and internal sources and tools of data and databases to create new pipelines as well as helping create analytics apps to be used by the traders, data scientists and quants.\n\nQualifications:\n• Computer science or related degree from a top university\n• 3+ years experience in Python, Beautiful Soup, Selenium, etc.\n• Experience with AWS, docker, Kubernetes are all a plus\n\nIndustry-leading compensation on offer with exceptional bonuses\n\nIf interested please get in touch by applying or at Volkan.ozbicer@radleyjames.com with your resume if you have further questions.",
      job_is_remote: false,
      job_posted_at_timestamp: 1694595106,
      job_posted_at_datetime_utc: "2023-09-13T08:51:46.000Z",
      job_city: "Houston",
      job_state: "TX",
      job_country: "US",
      job_latitude: 29.760427,
      job_longitude: -95.369804,
      job_benefits: null,
      job_google_link:
        "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=ZLHPTnm0vUZhlFhdAAAAAA%3D%3D",
      job_offer_expiration_datetime_utc: null,
      job_offer_expiration_timestamp: null,
      job_required_experience: {
        no_experience_required: false,
        required_experience_in_months: 36,
        experience_mentioned: true,
        experience_preferred: true,
      },
      job_required_skills: null,
      job_required_education: {
        postgraduate_degree: false,
        professional_certification: false,
        high_school: false,
        associates_degree: false,
        bachelors_degree: false,
        degree_mentioned: false,
        degree_preferred: false,
        professional_certification_mentioned: false,
      },
      job_experience_in_place_of_education: false,
      job_min_salary: null,
      job_max_salary: null,
      job_salary_currency: null,
      job_salary_period: null,
      job_highlights: {
        Qualifications: [
          "Computer science or related degree from a top university",
          "3+ years experience in Python, Beautiful Soup, Selenium, etc",
        ],
        Responsibilities: [
          "This individual will be working on expanding their global analytics and trading-related tools and APIs, liaising between external and internal sources and tools of data and databases to create new pipelines as well as helping create analytics apps to be used by the traders, data scientists and quants",
        ],
        Benefits: [
          "Industry-leading compensation on offer with exceptional bonuses",
        ],
      },
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113200",
      job_onet_job_zone: "4",
    },
  ],
} as const;

export const jobSearchFilterResponse = {
  status: "OK",
  request_id: "e7380661-e21b-4af0-87e6-db9e5a66c2ec",
  parameters: {
    query: "Python developer",
  },
  data: {
    categories: [],
    job_titles: [
      {
        name: "Senior",
        value: "c2VuaW9y",
        est_count: 20,
      },
      {
        name: "Engineer",
        value: "ZW5naW5lZXI=",
        est_count: 1,
      },
      {
        name: "Expertise",
        value: "ZXhwZXJ0aXNl",
        est_count: 1,
      },
      {
        name: "Software engineer",
        value: "c29mdHdhcmUgZW5naW5lZXI=",
        est_count: 1,
      },
      {
        name: "Data engineer",
        value: "ZGF0YSBlbmdpbmVlcg==",
        est_count: 1,
      },
      {
        name: "Exp",
        value: "ZXhw",
        est_count: 1,
      },
      {
        name: "Programmer",
        value: "cHJvZ3JhbW1lcg==",
        est_count: 1,
      },
      {
        name: "With experience",
        value: "d2l0aCBleHBlcmllbmNl",
        est_count: 1,
      },
      {
        name: "Automation",
        value: "YXV0b21hdGlvbg==",
        est_count: 1,
      },
      {
        name: "Backend engineer",
        value: "YmFja2VuZCBlbmdpbmVlcg==",
        est_count: 1,
      },
      {
        name: "Business",
        value: "YnVzaW5lc3M=",
        est_count: 1,
      },
      {
        name: "Computer",
        value: "Y29tcHV0ZXI=",
        est_count: 1,
      },
      {
        name: "Principal",
        value: "cHJpbmNpcGFs",
        est_count: 1,
      },
      {
        name: "Principal consultant",
        value: "cHJpbmNpcGFsIGNvbnN1bHRhbnQ=",
        est_count: 1,
      },
      {
        name: "Senior staff",
        value: "c2VuaW9yIHN0YWZm",
        est_count: 1,
      },
      {
        name: "Software engineering",
        value: "c29mdHdhcmUgZW5naW5lZXJpbmc=",
        est_count: 1,
      },
      {
        name: "Specialist",
        value: "c3BlY2lhbGlzdA==",
        est_count: 1,
      },
      {
        name: "Stack engineer",
        value: "c3RhY2sgZW5naW5lZXI=",
        est_count: 1,
      },
      {
        name: "Volunteer",
        value: "dm9sdW50ZWVy",
        est_count: 1,
      },
    ],
    company_types: [
      {
        name: "Computer Services",
        value: "L2J1c2luZXNzL25haWNzMjAwNy81NDE1OkNvbXB1dGVyIFNlcnZpY2Vz",
        est_count: 110,
      },
      {
        name: "Staffing",
        value: "L2J1c2luZXNzL25haWNzMjAwNy81NjEzOlN0YWZmaW5n",
        est_count: 1,
      },
      {
        name: "Information",
        value: "L2J1c2luZXNzL25haWNzMjAwNy81MTpJbmZvcm1hdGlvbg==",
        est_count: 1,
      },
      {
        name: "Consulting",
        value: "L2J1c2luZXNzL25haWNzMjAwNy81NDE2OkNvbnN1bHRpbmc=",
        est_count: 1,
      },
      {
        name: "Finance",
        value: "L2J1c2luZXNzL25haWNzMjAwNy81MjpGaW5hbmNl",
        est_count: 1,
      },
      {
        name: "Manufacturing",
        value: "L2J1c2luZXNzL25haWNzMjAwNy8zMTpNYW51ZmFjdHVyaW5n",
        est_count: 1,
      },
      {
        name: "Construction",
        value: "L2J1c2luZXNzL25haWNzMjAwNy8yMzpDb25zdHJ1Y3Rpb24=",
        est_count: 1,
      },
      {
        name: "Education",
        value: "L2J1c2luZXNzL25haWNzMjAwNy82MTpFZHVjYXRpb24=",
        est_count: 1,
      },
      {
        name: "Engineering Services",
        value: "L2J1c2luZXNzL25haWNzMjAwNy81NDEzOkVuZ2luZWVyaW5nIFNlcnZpY2Vz",
        est_count: 1,
      },
    ],
    employers: [
      {
        name: "Upwork",
        value: "L20vMDJwemg1ZDpVcHdvcms=",
        est_count: 110,
      },
      {
        name: "ITech Solutions",
        value: "L2cvMTFjNzN2bGQ5ZzppVGVjaCBTb2x1dGlvbnM=",
        est_count: 1,
      },
      {
        name: "Saxon Global",
        value: "L2cvMTFkeW1jeDVoYzpTYXhvbiBHbG9iYWw=",
        est_count: 1,
      },
      {
        name: "ConsultNet",
        value: "L2cvMWR0emc1X3k6Q29uc3VsdE5ldA==",
        est_count: 1,
      },
      {
        name: "Donato Technologies, Inc.",
        value: "L2cvMTFwcjZ5bWpoODpEb25hdG8gVGVjaG5vbG9naWVzLCBJbmMu",
        est_count: 1,
      },
      {
        name: "IT America Inc",
        value: "L2cvMTFkeHBreHlwYzpJVCBBbWVyaWNhIEluYw==",
        est_count: 1,
      },
      {
        name: "IVY TECH SOLUTIONS INC",
        value: "L2cvMTFreHhycWx2dDpJVlkgVEVDSCBTT0xVVElPTlMgSU5D",
        est_count: 1,
      },
      {
        name: "Insight Global",
        value: "L20vMGI3NzN6cTpJbnNpZ2h0IEdsb2JhbA==",
        est_count: 1,
      },
      {
        name: "Lorven Technologies Inc.",
        value: "L2cvMTFjNzNmdzFjeTpMb3J2ZW4gVGVjaG5vbG9naWVzIEluYy4=",
        est_count: 1,
      },
      {
        name: "MethodHub",
        value: "L2cvMTFyazI3cHo0bjpNZXRob2RIdWI=",
        est_count: 1,
      },
      {
        name: "Point72",
        value: "L20vMDZicXdxOlBvaW50NzI=",
        est_count: 1,
      },
      {
        name: "TEKsystems",
        value: "L2cvMTFiNmc0Ymt2MDpURUtzeXN0ZW1z",
        est_count: 1,
      },
      {
        name: "3XM Group",
        value: "L2cvMTFrcTh2Zm1fNzozWE0gR3JvdXA=",
        est_count: 1,
      },
      {
        name: "Actalent",
        value: "L2cvMTFyc3JobmRfeDpBY3RhbGVudA==",
        est_count: 1,
      },
      {
        name: "Advanced Knowledge Tech LLC",
        value: "L2cvMTF0Y24wMjhyejpBZHZhbmNlZCBLbm93bGVkZ2UgVGVjaCBMTEM=",
        est_count: 1,
      },
      {
        name: "Agama Solutions",
        value: "L2cvMTFkeHEyNTFkajpBZ2FtYSBTb2x1dGlvbnM=",
        est_count: 1,
      },
      {
        name: "Altair Data Resources, Inc.",
        value: "L2cvMTFnOW1fOW1maDpBbHRhaXIgRGF0YSBSZXNvdXJjZXMsIEluYy4=",
        est_count: 1,
      },
      {
        name: "Bosch Group",
        value: "L20vMDFobmtmOkJvc2NoIEdyb3Vw",
        est_count: 1,
      },
      {
        name: "By Light Professional IT Services LLC",
        value:
          "L2cvMTFmeTIwOXA5NzpCeSBMaWdodCBQcm9mZXNzaW9uYWwgSVQgU2VydmljZXMgTExD",
        est_count: 1,
      },
      {
        name: "COCOLEVIO",
        value: "L2cvMTFya2N0ZjVmMjpDT0NPTEVWSU8=",
        est_count: 1,
      },
      {
        name: "ClientSolv",
        value: "L2cvMTFnNzBjc3djYjpDbGllbnRTb2x2",
        est_count: 1,
      },
      {
        name: "Compunnel Inc.",
        value: "L2cvMTFmMDFrMGw0XzpDb21wdW5uZWwgSW5jLg==",
        est_count: 1,
      },
      {
        name: "ConstructConnect",
        value: "L2cvMTFiYzZsZnhmdDpDb25zdHJ1Y3RDb25uZWN0",
        est_count: 1,
      },
      {
        name: "Diverse Lynx",
        value: "L2cvMTFkeHBfNDlyXzpEaXZlcnNlIEx5bng=",
        est_count: 1,
      },
      {
        name: "ECS",
        value: "L2cvMTFyXzZxeDZ6OkVDUw==",
        est_count: 1,
      },
      {
        name: "EastBanc Technologies",
        value: "L2cvMTFkeHEzOHp0ZDpFYXN0QmFuYyBUZWNobm9sb2dpZXM=",
        est_count: 1,
      },
    ],
    date_posted: [
      {
        name: "Past day",
        value: "today",
        est_count: 20,
      },
      {
        name: "Past 3 days",
        value: "3days",
        est_count: 40,
      },
      {
        name: "Past week",
        value: "week",
        est_count: 150,
      },
      {
        name: "Past month",
        value: "month",
        est_count: 220,
      },
    ],
    employment_types: [
      {
        name: "Contractor",
        value: "CONTRACTOR",
        est_count: 170,
      },
      {
        name: "Full-time",
        value: "FULLTIME",
        est_count: 150,
      },
      {
        name: "Part-time",
        value: "PARTTIME",
        est_count: 10,
      },
      {
        name: "Internship",
        value: "INTERN",
        est_count: 1,
      },
    ],
    job_requirements: [
      {
        name: "No degree",
        value: "no_degree",
        est_count: 200,
      },
      {
        name: "No experience",
        value: "no_experience",
        est_count: 60,
      },
      {
        name: "Under 3 years of experience",
        value: "under_3_years_experience",
        est_count: 10,
      },
      {
        name: "3+ years of experience",
        value: "more_than_3_years_experience",
        est_count: 100,
      },
    ],
  },
} as const;

export const latestJobsData = [
  {
    employer_name: "Dice",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKlgydP7sElaJC9qPrtNHwBhyTMHYgii1RPWsy&s=0",
    employer_website: null,
    employer_company_type: "Information",
    job_publisher: "LinkedIn",
    job_id: "8yv3oA_2-UYAAAAAAAAAAA==",
    job_employment_type: "CONTRACTOR",
    job_title: "Web Developer - 6-month Contract - Houston Hybrid",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/web-developer-6-month-contract-houston-hybrid-at-dice-3624857671",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5805,
    num_applicants: 10,
    job_description:
      "An established energy client of mine is looking for an experienced Web Developer to join their team on an initial 6-month contract. Starting 6/5, you will be working in an agile team to help develop a new set of web applications for their own system and sub vendors. This role is hybrid and you will be required to go in to the office 3 days p/w. Full-Stack Web Developer 6-month contract (likely extension) Houston - Hybrid working W2 - $70 - $75 p/h C2C - $80 - $90 p/h Starting 06/05 Technical requirements; JavaScript, (React OR Angular OR Vue), Node, HTML, CSS, Kubernetes, API (NO EMPLOYERS OR RECRUTIERS) Oscar Associates Limited (US) is acting as an Employment Business in relation to this vacancy. Web Developer - 6-month Contract - Houston Hybrid",
    job_is_remote: true,
    job_posted_at_timestamp: 1685653019,
    job_posted_at_datetime_utc: "2023-06-01T20:56:59.000Z",
    job_city: "Houston",
    job_state: "TX",
    job_country: "US",
    job_latitude: 29.760427,
    job_longitude: -95.369804,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=web+developer+in+texas+usa&start=0&ibp=htl;,jobs#fpstate=tldetail&htivrt=jobs&htiq=web+developer+in+texas+usa&htidocid=8yv3oA_2-UYAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-07-01T20:56:59.000Z",
    job_offer_expiration_timestamp: 1688245019,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    // job_required_skills: [
    //   "JavaScript",
    //   "React",
    //   "React",
    //   "Node",
    //   "HTML",
    //   "CSS",
    //   "API",
    // ],
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "JavaScript, (React OR Angular OR Vue), Node, HTML, CSS, API",
        "Job Requirements: Bachelor’s degree or foreign degree equivalent in Computer Science, Engineering or related field and five (5) years of experience in the job offered or related role",
        "Skills: Experience and/or education must include: Experience in programming applications using HTML, JavaScript, CSS, Angular/React Js, XML and Json.; SQL/No-SQL databases; Experience working with the continuous integration and continuous deployment (CI/CD) pipelines; Experience in programming applications using Java/J2EE; Understanding of software quality assurance principles; Experience working in Agile teams",
        "Python, React, Linux, Unix, API",
        "Strong development experience using Python, REST API Service",
        "Database development skills, experience with Object-oriented and Relational databases - SQL Server/Oracle/Sybase",
        "Experience developing software using Agile methodology",
        "Knowledge of JIRA tools and Continuous Integration capabilities",
        "Hands on experience in writing unit and UI integration test cases",
      ],
      Responsibilities: [
        "Starting 6/5, you will be working in an agile team to help develop a new set of web applications for their own system and sub vendors",
        "This role is hybrid and you will be required to go in to the office 3 days p/w",
      ],
      benefits: [
        "6-month contract (likely extension)",
        "W2 - $70 - $75 p/h",
        "C2C - $80 - $90 p/h",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
    job_naics_code: "519130",
    job_naics_name:
      "Internet Publishing and Broadcasting and Web Search Portals",
  },
];
